# Generated by Django 3.2.6 on 2021-08-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
